-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Analysis" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "modelName" TEXT NOT NULL,
    "provider" TEXT,
    "providerFallbackInfo" TEXT,
    "projectSummary" TEXT NOT NULL,
    "problemDefinition" TEXT NOT NULL,
    "complexityScore" INTEGER NOT NULL,
    "estimatedDurationWeeks" INTEGER NOT NULL,
    "requiredSkillLevel" TEXT NOT NULL,
    "targetUsersJson" TEXT,
    "mvpScopeJson" TEXT,
    "coreFeaturesJson" TEXT,
    "alternativeStacksJson" TEXT,
    "modulesJson" TEXT,
    "assumptions" TEXT,
    "missingInformationQuestions" TEXT,
    "projectMaturityAnalysis" TEXT,
    "platformRecommendation" TEXT,
    "codingAgentRecommendation" TEXT,
    "languageRecommendation" TEXT,
    "runtimeRecommendation" TEXT,
    "packageManagerRecommendation" TEXT,
    "frontendFrameworkRecommendation" TEXT,
    "backendFrameworkRecommendation" TEXT,
    "databaseRecommendation" TEXT,
    "ormRecommendation" TEXT,
    "uiStylingRecommendation" TEXT,
    "testingRecommendation" TEXT,
    "deploymentRecommendation" TEXT,
    "recommendedStackJson" TEXT NOT NULL,
    "rejectedAlternativesJson" TEXT,
    "architectureOverview" TEXT,
    "systemModulesJson" TEXT,
    "uiPagePlanJson" TEXT,
    "databaseSchemaJson" TEXT,
    "apiEndpointsJson" TEXT,
    "developmentRoadmapJson" TEXT,
    "taskBreakdownJson" TEXT,
    "promptQualityScoreJson" TEXT,
    "generatedPromptDraftJson" TEXT,
    "finalPromptJson" TEXT,
    "promptSectionsJson" TEXT,
    "acceptanceCriteriaJson" TEXT,
    "testPlanJson" TEXT,
    "risksJson" TEXT,
    "futureImprovementsJson" TEXT,
    "rawAiResponseJson" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Analysis_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_Analysis" ("alternativeStacksJson", "apiEndpointsJson", "complexityScore", "coreFeaturesJson", "createdAt", "databaseSchemaJson", "developmentRoadmapJson", "estimatedDurationWeeks", "futureImprovementsJson", "id", "modelName", "modulesJson", "mvpScopeJson", "problemDefinition", "projectId", "projectSummary", "rawAiResponseJson", "recommendedStackJson", "requiredSkillLevel", "risksJson", "targetUsersJson") SELECT "alternativeStacksJson", "apiEndpointsJson", "complexityScore", "coreFeaturesJson", "createdAt", "databaseSchemaJson", "developmentRoadmapJson", "estimatedDurationWeeks", "futureImprovementsJson", "id", "modelName", "modulesJson", "mvpScopeJson", "problemDefinition", "projectId", "projectSummary", "rawAiResponseJson", "recommendedStackJson", "requiredSkillLevel", "risksJson", "targetUsersJson" FROM "Analysis";
DROP TABLE "Analysis";
ALTER TABLE "new_Analysis" RENAME TO "Analysis";
CREATE UNIQUE INDEX "Analysis_projectId_key" ON "Analysis"("projectId");
CREATE TABLE "new_Project" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "targetPlatform" TEXT NOT NULL,
    "difficultyLevel" TEXT NOT NULL,
    "priority" TEXT NOT NULL,
    "preferredTechnologies" TEXT,
    "roadmapDurationWeeks" INTEGER NOT NULL DEFAULT 8,
    "schemaVersion" TEXT NOT NULL DEFAULT '1.0',
    "aiProvider" TEXT,
    "selectedModel" TEXT,
    "providerFallbackInfo" TEXT,
    "outputMode" TEXT DEFAULT 'full_project_plan',
    "planMode" TEXT DEFAULT 'plan_first',
    "outputDepth" TEXT DEFAULT 'detailed',
    "codingAgent" TEXT DEFAULT 'auto',
    "projectMaturity" TEXT DEFAULT 'just_idea',
    "programmingLanguage" TEXT DEFAULT 'auto',
    "runtime" TEXT DEFAULT 'auto',
    "packageManager" TEXT DEFAULT 'auto',
    "frontendFramework" TEXT DEFAULT 'auto',
    "backendFramework" TEXT DEFAULT 'auto',
    "database" TEXT DEFAULT 'auto',
    "orm" TEXT DEFAULT 'auto',
    "uiStyling" TEXT DEFAULT 'auto',
    "testing" TEXT DEFAULT 'auto',
    "deployment" TEXT DEFAULT 'auto',
    "requirementToggles" TEXT,
    "customInstructions" TEXT,
    "status" TEXT NOT NULL DEFAULT 'analyzing',
    "errorMessage" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_Project" ("createdAt", "description", "difficultyLevel", "id", "preferredTechnologies", "priority", "roadmapDurationWeeks", "status", "targetPlatform", "title", "updatedAt") SELECT "createdAt", "description", "difficultyLevel", "id", "preferredTechnologies", "priority", "roadmapDurationWeeks", "status", "targetPlatform", "title", "updatedAt" FROM "Project";
DROP TABLE "Project";
ALTER TABLE "new_Project" RENAME TO "Project";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
