import type { Request, Response } from "express";
import { projectInputSchema, v2ProjectInputSchema } from "../schemas/projectInputSchema.js";
import { ApiError } from "../utils/ApiError.js";
import {
  analyzeProject,
  deleteProject,
  getAnalysisForExport,
  getProjectById,
  listProjects,
  analyzeProjectV2,
  regeneratePrompt,
  patchPromptDraft,
  finalizePrompt,
} from "../services/projectService.js";
import {
  buildMarkdownExportV2,
  buildJsonExportPayload,
  buildAgentsMdExport,
  buildTxtExport,
} from "../services/exportService.js";
import { getAgentById } from "../services/agentRegistryService.js";

export async function analyzeProjectController(
  req: Request,
  res: Response,
): Promise<void> {
  // Try v2 schema first
  const v2Parsed = v2ProjectInputSchema.safeParse(req.body);
  if (v2Parsed.success) {
    const result = await analyzeProjectV2(v2Parsed.data);
    res.status(201).json(result);
    return;
  }

  // Fallback to v1 schema
  const v1Parsed = projectInputSchema.safeParse(req.body);
  if (!v1Parsed.success) {
    throw new ApiError(400, "BAD_REQUEST", "Invalid request body.", v1Parsed.error.flatten());
  }

  const result = await analyzeProject(v1Parsed.data);
  res.status(201).json(result);
}

export async function listProjectsController(
  _req: Request,
  res: Response,
): Promise<void> {
  const projects = await listProjects();
  res.json(projects);
}

export async function getProjectController(
  req: Request,
  res: Response,
): Promise<void> {
  const project = await getProjectById(req.params.id);
  res.json(project);
}

export async function deleteProjectController(
  req: Request,
  res: Response,
): Promise<void> {
  await deleteProject(req.params.id);
  res.status(204).send();
}

export async function exportJsonController(
  req: Request,
  res: Response,
): Promise<void> {
  const { project, analysis, ai } = await getAnalysisForExport(req.params.id);
  const payload = buildJsonExportPayload(project, analysis, ai);
  const filename = `roadmind-${project.id}.json`;
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${filename}"`,
  );
  res.send(JSON.stringify(payload, null, 2));
}

export async function exportMarkdownController(
  req: Request,
  res: Response,
): Promise<void> {
  const { project, ai } = await getAnalysisForExport(req.params.id);
  const md = buildMarkdownExportV2(project, ai);
  const filename = "roadmind-technical-report.md";
  res.setHeader("Content-Type", "text/markdown; charset=utf-8");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${filename}"`,
  );
  res.send(md);
}

export async function exportTxtController(
  req: Request,
  res: Response,
): Promise<void> {
  const { project, ai } = await getAnalysisForExport(req.params.id);
  const txt = buildTxtExport(project, ai);
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="roadmind-master-prompt.txt"`);
  res.send(txt);
}

export async function exportAgentsMdController(
  req: Request,
  res: Response,
): Promise<void> {
  const { project, ai } = await getAnalysisForExport(req.params.id);
  const md = buildAgentsMdExport(project, ai);
  res.setHeader("Content-Type", "text/markdown; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="AGENTS.md"`);
  res.send(md);
}


export async function exportAgentPromptController(
  req: Request,
  res: Response,
): Promise<void> {
  const { project, ai } = await getAnalysisForExport(req.params.id);
  const agentId = req.params.agent;
  const agent = getAgentById(agentId);
  if (!agent) {
    throw new ApiError(404, "NOT_FOUND", "Agent not found.");
  }

  // Generate agent-specific prompt
  const agentPromptContent = [
    `# ${agent.displayName} Prompt`,
    "",
    `## ${project.title}`,
    "",
    ai.generatedPromptDraft?.fullPrompt || ai.projectSummary || "",
    "",
    "---",
    `*Generated by Roadmind v2.0 for ${agent.displayName}*`,
  ].join("\n");

  res.setHeader("Content-Type", "text/markdown; charset=utf-8");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="${agent.outputFileRecommendation}"`,
  );
  res.send(agentPromptContent);
}

export async function regeneratePromptController(
  req: Request,
  res: Response,
): Promise<void> {
  const id = req.params.id;
  const { customInstructions, enabledSections } = req.body as {
    customInstructions?: string;
    enabledSections?: string[];
  };

  const result = await regeneratePrompt(id, customInstructions, enabledSections);
  res.json(result);
}

export async function patchPromptDraftController(
  req: Request,
  res: Response,
): Promise<void> {
  const id = req.params.id;
  const draft = req.body.draft as Record<string, unknown> | undefined;

  if (!draft) {
    throw new ApiError(400, "BAD_REQUEST", "Draft is required.");
  }

  await patchPromptDraft(id, draft as AIOutputV2["generatedPromptDraft"]);
  res.status(204).send();
}

export async function finalizePromptController(
  req: Request,
  res: Response,
): Promise<void> {
  const id = req.params.id;
  const { enabledSections } = req.body as { enabledSections?: string[] };

  const result = await finalizePrompt(id, enabledSections);
  res.json(result);
}

import type { AIOutputV2 } from "../schemas/aiOutputSchema.js";
